# in _config.yml
title: "Open Hardware Academy"
logo: img/logo.png
author: TU Delft DCC
execute:
  execute_notebooks: "off"

only_build_toc_files: true

exclude_patterns: [ /images/**.*,./**/*.py, ./**/*.jpg, LICENSE.md ]

# Information about where the book exists on the web
repository:
  url  : https://github.com/TU-Delft-DCC/TU-Delft-DCC.github.io.git

html:
  use_repository_button: true
  comments:
    utterances:
      repo: "TU-Delft-DCC/TU-Delft-DCC.github.io.git" 
    
  use_edit_page_button: true

  extra_footer: |
      <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
  
  
  
  home_page_in_navbar: true

sphinx:
    config:
      html_show_copyright: false